enum ReadDtcIndex {
  UDS_3BYTE_DTC,
  UDS_2BYTE12_DTC,
  UDS_2BYTE13_DTC,
  KWP_2BYTE_DTC,
  GENERIC_OBD,
  UDS,
  KWP_PRIMITIVE,
}

enum ClearDtcIndex { UDS_4BYTES, UDS_3BYTES, GENERIC_OBD, KWP, KWP_PRIMITIVE }
